void f() {
    throw new MyException()
}

try {
    f()
} catch(MyException e) {
    println "CATCH: $e"
}

class MyException extends Exception { }
