class SimpleException extends Exception {}

class CustomException extends Exception {
	void CustomException(string msg) {
		super.Exception(msg)
	}
}

bool okCatch, okFinally

void func() {
	try {
		throw new CustomException("My message")
	} catch (SimpleException e) {
		println "Catch"
		okCatch = true
	} finally {
		println "Finaly"
		okFinally = true
	}
}

void testFoo() {
	func()
	assert(okCatch)
	assert(okFinally)
}

